### ISSUE TITLE
p-tags in dd

### ISSUE THREAD

**Issue by lisardo2** [kitzberger/rte_ckeditor_dl#1]
Hello, 

the plugin adds randomly `<p>` around the content of the `<dd>`-Tags. And the last `<dd>` gets an `<p>&nbsp;</p>` which results in an empty line at the end of the list which cannot removed.

**Comment by kitzberger** [comment]
What version of TYPO3 are you using?

**Comment by lisardo2** [comment]
Hi Philipp,

i use TYPO3 8.7.27

thanks!
Peter


> Am 05.08.2019 um 18:17 schrieb Philipp Kitzberger <notifications@github.com>:
> 
> What version of TYPO3 are you using?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
-----------------------------------------------
Peter Linzenkirchner
Lisardo EDV-Beratung
Katharinengasse 20, Rückgebäude,
Eingang Bleigäßchen 5
86150 Augsburg
Tel. +49-821-150565, Fax +49-821-150595
http://typo3-lisardo.de
info@lisardo.de
-----------------------------------------------

**Comment by kitzberger** [comment]
Thanks for the info, @lisardo2 ;-)

I've just had a look at this.

Source mode in RTE looks fine:
![Bildschirmfoto vom 2019-08-05 22-40-20](https://user-images.githubusercontent.com/1405149/62494176-21872c00-b7d3-11e9-951a-51c134d7c83e.png)

The markup in the DB as well:
![Bildschirmfoto vom 2019-08-05 22-42-49](https://user-images.githubusercontent.com/1405149/62494175-21872c00-b7d3-11e9-8df2-dcf4adffcca6.png)

But in the frontend it's exactly as you've described:
![Bildschirmfoto vom 2019-08-05 22-44-45](https://user-images.githubusercontent.com/1405149/62494174-21872c00-b7d3-11e9-828f-e7beedef2a4b.png)

So the cause must be somewhere in lib.parseFunc_RTE.

As you can see the TYPO3 core defines two rules for handling <dl> tags:
![Bildschirmfoto vom 2019-08-05 22-56-26](https://user-images.githubusercontent.com/1405149/62494739-74151800-b7d4-11e9-9113-758618856def.png)

Removing the `callRecursive = 1` with the following TypoScript:
```
lib.parseFunc_RTE.externalBlocks.dl.callRecursive >
```
would remove the nonsense <p> tags you've mentioned but would also break any markup (such as typolinks!) within the <dl> list as shown in this example:
![Bildschirmfoto vom 2019-08-05 22-55-51](https://user-images.githubusercontent.com/1405149/62494928-da9a3600-b7d4-11e9-9737-ce1fbb8cc30b.png)

So I expect the following TypoScript to do the trick here:
```
lib.parseFunc_RTE.externalBlocks.dl.callRecursive >
lib.parseFunc_RTE.externalBlocks.dl.stdWrap.parseFunc =< lib.parseFunc
```

Can you test this please and give me some feedback on it? I'll add it to the extensions description then...

Cheers, Philipp

**Comment by lisardo2** [comment]
Hello Philipp,

lib.parseFunc_RTE.externalBlocks.dl.callRecursive >
lib.parseFunc_RTE.externalBlocks.dl.stdWrap.parseFunc =< lib.parseFunc

=> thats it! Very good, it really does the trick!

Many thanks for your efforts!
Is there a possibility to donate? You really earned a few bottles :-)

Cheers
Peter


> Am 05.08.2019 um 23:05 schrieb Philipp Kitzberger <notifications@github.com>:
> 
> Thanks for the info, @lisardo2 ;-)
> 
> I've just had a look at this.
> 
> Source mode in RTE looks fine:
> 
> 
> The markup in the DB as well:
> 
> 
> But in the frontend it's exactly as you've described:
> 
> 
> So the cause must be somewhere in lib.parseFunc_RTE.
> 
> As you can see the TYPO3 core defines two rules for handling
> 
> tags:
> 
> 
> Removing the callRecursive = 1 with the following TypoScript:
> 
> lib.parseFunc_RTE.externalBlocks.dl.callRecursive >
> 
> would remove the nonsense
> 
> tags you've mentioned but would also break any markup (such as typolinks!) within the
> 
> list as shown in this example:
> 
> 
> So I expect the following TypoScript to do the trick here:
> 
> lib.parseFunc_RTE.externalBlocks.dl.callRecursive >
> lib.parseFunc_RTE.externalBlocks.dl.stdWrap.parseFunc =< lib.parseFunc
> 
> Can you test this please and give me some feedback on it? I'll add it to the extensions description then...
> 
> Cheers, Philipp
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
-----------------------------------------------
Peter Linzenkirchner
Lisardo EDV-Beratung
Katharinengasse 20, Rückgebäude,
Eingang Bleigäßchen 5
86150 Augsburg
Tel. +49-821-150565, Fax +49-821-150595
http://typo3-lisardo.de
info@lisardo.de
-----------------------------------------------

**Comment by kitzberger** [comment]
Hi Peter,
awww, thanks! No need to donate anything though. Maybe just give some spare change to the next homeless person you'll encounter and think of me, hehe ;-)
Cheers, Philipp
